# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 17:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('adress', models.CharField(max_length=250)),
                ('home_number', models.CharField(max_length=8, null=True)),
                ('zipcode', models.CharField(max_length=8)),
                ('income', models.IntegerField()),
                ('income_partner', models.IntegerField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('bkr', models.CharField(choices=[('nee', 'Geen bkr codering'), ('ja', 'Wel een bkr codering'), ('hersteld', 'Ja, hersteld')], max_length=8)),
                ('calculationDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'leads',
            },
        ),
    ]
