# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('adress', models.CharField(max_length=250)),
                ('homeNumber', models.IntegerField()),
                ('zipcode', models.CharField(max_length=8)),
                ('income', models.IntegerField()),
                ('income_partner', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('bkr', models.CharField(choices=[('nee', 'Geen bkr codering'), ('ja', 'Wel een bkr codering'), ('hersteld', 'Ja, hersteld')], max_length=1)),
                ('calculationDate', models.DateField()),
            ],
        ),
    ]
