# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leads',
            options={'verbose_name_plural': 'leads'},
        ),
        migrations.AlterField(
            model_name='leads',
            name='bkr',
            field=models.CharField(choices=[('nee', 'Geen bkr codering'), ('ja', 'Wel een bkr codering'), ('hersteld', 'Ja, hersteld')], max_length=8),
        ),
        migrations.AlterField(
            model_name='leads',
            name='calculationDate',
            field=models.DateField(null=True),
        ),
    ]
