# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170621_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='income_partner',
            field=models.IntegerField(blank=True),
        ),
    ]
