# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170621_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='homeNumber',
        ),
        migrations.AddField(
            model_name='leads',
            name='home_number',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
